### ISSUE TITLE
Refactor classes

### ISSUE THREAD

**Issue by VRSoorya** [AY2021S2-CS2103-T16-3/tp#127]
Name and ResidenceName could inherit from or implement a common Name class or interface respectively.

Possible but lower priority: start and end dates in Booking can be made into another class such as BookingTime and contain the doesOverlap and comparator methods.

**Comment by whatthelump** [comment]
To clarify, the current Name class should be more restrictive in the types of symbols accepted (people's names should not have special characters such as ^) while there are no restrictions for ResidenceName (apart from only whitespaces)?

**Comment by VRSoorya** [comment]
Yup such differentiation is possible and reasonable to accommodate residence names like Pinnacle@Duxton while having regular names for visitors
